### ISSUE TITLE
add changelog support

### ISSUE THREAD

**Issue by meesterdude** [reenhanced/gitreflow#100]
I usually am verbose about my PR messages; it's the place i do my brain dump of what i was thinking, issues I ran into, and so on. Sometimes I write nice commit messages that would work well in a changelog; others are just noise. 

ideally, we'd set a flag on review command that grabs the commits we wrote and formats them in a change log for us in the PR, and presents in editor for update

Might be a good idea to flag commits when creating them to be changelog specifically; or, maybe just delete ones that are noise when submitting the PR. 

However, changes can occur after a PR is submitted. So we'll want to think about what we do there; perhaps offer a direct way to regenerate the changelog, so we can at least copy in anything new. 

a starting point: `git log --pretty=format:"%B" --first-parent --no-merges master..branchname`

**Comment by codenamev** [comment]
This is a great idea.  I think we're going to close this in favor of #51 to create a commit template that would let you do this as well :smile:
