### ISSUE TITLE
add "Created With Reflow"

### ISSUE THREAD

**Issue by meesterdude** [reenhanced/gitreflow#101]
At the bottom of every PR, we can add the text "Created With Reflow" where reflow is a link to the project. Similar to "sent from my iphone"

This would need to be appended automatically; but for the most part appears at the bottom of the editor and can be easily nuked. 

Perhaps a personal setting can decide to disable this feature for good, should the user be bothered by it.

**Comment by codenamev** [comment]
@nhance, thoughts on this?  Personally if I was using gitreflow I wouldn't want to have to constantly delete this message from my PRs.

**Comment by codenamev** [comment]
Nice idea, but I think injecting an ad is not the right approach here.  Maybe a "Reflow-Enabled" "badge" that project maintainers could place on their Readme would be better suited for this?

**Comment by nhance** [comment]
Completely agree
