### ISSUE TITLE
message below the fold in review

### ISSUE THREAD

**Issue by meesterdude** [reenhanced/gitreflow#105]
Ideally, when I am presented the editor, this is what i'll see

```
rj_201_login_fix

this fixes 209 and should be good to go!

--end--

So, you're creating a PR? did you...

1. Write tests?
2. Add Documentation?
3. Merge in master?

```

Where, anything after `--end--` is sourced from a file that the project defines. So, projects can use reflow and define their own checklist to display (or whatever else) in the editor, as you create the PR.

we then just split on `--end--` and throw away anything after it, when creating the PR. 

However, one snag is either we force a specific file name in the app root, or have to have some kind of project-level config to define it.

**Comment by codenamev** [comment]
This can already be done with git alone.  See the git config `commit.template` for how to set this up.  I'll leave this open as a TODO to add a wiki page for how to set this up.

**Comment by codenamev** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;KOmjOmWx&#x2F;37-add-documentation-on-setting-up-commit-templates"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Add documentation on setting up commit templates</a>

**Comment by codenamev** [comment]
Closing this for now.  The documentation for git's built-in commit templates is pretty clear, as is Github's new flavor.
