### ISSUE TITLE
git reflow setup not working

### ISSUE THREAD

**Issue by AlexCppns** [reenhanced/gitreflow#106]
$ git reflow setup
Available remote Git Server services::
1. GitHub
2. BitBucket (team-owned repos only)
Which service would you like to use for this project?  1
Your GitHub account was already setup with: 
        User Name: 
        Endpoint: https://api.github.com

Let me know if you need more information.

**Comment by nhance** [comment]
Try the following to see what your github user has been set as: `git config --get-all github.user`

That will likely return an empty string, so you can assign the username like this:
`git config --global --replace-all github.user "AlexCppns"`

**Comment by nhance** [comment]
Please re-open if that doesn't fix it. You may need to edit your git config to remove the reflow settings as we don't have a way to wipe/reset everything yet
