### ISSUE TITLE
Error when running git reflow review

### ISSUE THREAD

**Issue by mikefsm** [reenhanced/gitreflow#107]
Just install the reflow gem and went through the setup. When I ran git reflow review on the branch I was working on I got the following message:
error: undefined method 'shift' for "git rev-parse --show-toplevel":String
error: undefined method 'strip' for 1:Fixnum 

Did this on my PC at work so I'm not sure if that is being goofy. I wasn't able to get resnet running locally on that machine but did on my Mac at home. Cloned a copy of the work I had done at home to my work machine and thought I could push up the changes for review using reflow.

Let me know if you need more info.

Thanks,

Mike Prince

**Comment by codenamev** [comment]
Fixed via https://github.com/reenhanced/gitreflow/commit/0f38dd7289c7533d880f80dbde43e4eea2e81f32
