### ISSUE TITLE
reflow needs an lgtm from myself

### ISSUE THREAD

**Issue by sethladd** [reenhanced/gitreflow#116]
Would it make sense for reflow not to require an lgtm from myself, if I've commented on the PR? Right now, I need to type lgtm into a comment on my PR before I can deliver a branch with reflow.

**Comment by codenamev** [comment]
I think that makes sense.  Care to submit a PR?

**Comment by sethladd** [comment]
Can't promise I'll get to it soon :) but good to know someone (me?) can fix it. Thanks!

**Comment by sethladd** [comment]
hm, just in case an edit to an existing comment doesn't trigger an email: @codenamev

**Comment by codenamev** [comment]
Thanks, did not get that email.

**Comment by sethladd** [comment]
https://github.com/reenhanced/gitreflow/pull/124
