### ISSUE TITLE
Option to silence the offer to open the PR in my browser?

### ISSUE THREAD

**Issue by sethladd** [reenhanced/gitreflow#117]
In order to make the workflow faster, what do you think about not prompting to open the PR at the end of `git reflow review` ?

`git reflow review --help` doesn't list an option to turn off that offer.

Many terminals will let a user click a URL, so perhaps we could just print out the PR URL, and if the user wants to visit there, they can click it.

**Comment by codenamev** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;iOihwkXp&#x2F;39-option-to-silence-the-offer-to-open-the-pr-in-browser"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Option to silence the offer to open the PR in browser</a>

**Comment by codenamev** [comment]
Fixed in v0.8.0 with 3b44510b7042f7aa6db76248aa52123145732c0a.  We opted to just remove that "feature" to open links in a browser.  No one on our team has ever used it.

**Comment by sethladd** [comment]
Thanks!
