### ISSUE TITLE
No help from git reflow --help

### ISSUE THREAD

**Issue by sethladd** [reenhanced/gitreflow#118]
Hi,

What do you think about printing options from a `git reflow --help` ?

```
~/Code/dartdoc/test_package[sl-dual-nav] $ git reflow --help
No manual entry for git-reflow
```

**Comment by codenamev** [comment]
I like that idea, I'll flag this as a feature

**Comment by sethladd** [comment]
Thanks!

**Comment by simonzhu24** [comment]
@sethladd Actually the correct command that you want to run to get help for tools built on GLI is:

`git reflow help `

**Comment by codenamev** [comment]
As a command line tool, `--help` is a standard we should support.  I think this is as easy as adding a global flag?

**Comment by simonzhu24** [comment]
Yup, working on it !

**Comment by simonzhu24** [comment]
@codenamev, @sethladd 

In using the GLI tool:

"--help is special, and it's there as an alias for `app help`.  The idea is if you want help on a specific command, you'd do `app help command`.  So, unfortunately, having --help do more than get global help isn't something it does right now."

Dave (Owner of the https://github.com/davetron5000/gli repository)

**Comment by codenamev** [comment]
hmm... `git reflow start --help` seemed to work for me.  I'm going to leave this open to try and figure out what's going on here.  Seems the GLI syntax may have changed that's not allowing the root command to run proxy the `--help`

**Comment by simonzhu24** [comment]
@codenamev GLI does not support the generic command level --help option. 
`git reflow --help` for help on all reflow commands is not supported. In this case, you want to use GLI's `git reflow --help` instead. However GLI does support --help as both options and global_options for each individual command parsed. So you can run `git reflow start --help` or `git reflow review --help`.

**Comment by simonzhu24** [comment]
@codenamev can we close this issue? or is there further investigation required?

**Comment by codenamev** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;lI1OYczE&#x2F;40-no-help-from-git-reflow-help"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> No help from git reflow --help</a>

**Comment by simonzhu24** [comment]
@codenamev The link you mentioned brings me to a 404, Card is not found...

**Comment by codenamev** [comment]
Fixed in https://github.com/reenhanced/gitreflow/commit/af251a4360de39346783c94630683e778ac350d6
