### ISSUE TITLE
Don't open EDITOR if there is an existing PR for this branch

### ISSUE THREAD

**Issue by sethladd** [reenhanced/gitreflow#123]
Hi,

Here's a scenario:

* git reflow start sl-test
* git commit
* git commit
* git reflow review
  * EDITOR pops up, I replace sl-test with description of feature
  * save/close editor
* (later)
* git commit
* git commit
* git reflow review
  * EDITOR pops up, populated with sl-test (again)

Expected: no EDITOR pops up on second run of review (I suppose?... I assume that because I already set the description on the first review, I don't need to do it again)

Actual: EDITOR pops up on second run of review, populated with original branch name

Thanks for your thoughts!

**Comment by codenamev** [comment]
I'm with you on this, and I find myself constantly closing out the editor.  The way this was originally implemented was done asking to fill that info _before_ checking for an existing pull request.  I'll mark this as a todo to check for an existing PR before prompting for this.

**Comment by sethladd** [comment]
Yes, that would be a big help! Thanks.

**Comment by codenamev** [comment]
Fixed in `0.7.2`
