### ISSUE TITLE
Feature Request: command to cleanly land a contributor's PR

### ISSUE THREAD

**Issue by sethladd** [reenhanced/gitreflow#128]
Consider the case where a project gets a sweet PR from a contributor. Everything is great. lgtm. Now, how do I cleanly land that?

I'd love a reflow command that takes a PR from a contributor and "does the right thing".

Thanks!

**Comment by sethladd** [comment]
If we had this, we wouldn't need the big green Merge button from the Github UI.

**Comment by codenamev** [comment]
We have this on the top of the roadmap.  Dup of #103 (I think), and I left an outline of how we handle this internally.  Let's move the conversation there.
