### ISSUE TITLE
Request: git reflow review --quick or --update

### ISSUE THREAD

**Issue by sethladd** [reenhanced/gitreflow#129]
If I already have a review in progress, then the current `git reflow review` process is a bit lengthy and duplicates a lot. Might I suggest a `--quick` or `--update` option?

* don't open EDITOR
* don't prompt me to submit the PR (just do it)
* don't prompt me to open in browser

This way, if the PR already exists, just update the review, and don't prompt me. Right now, I need to confirm the EDITOR, confirm the PR, and say no to opening the browser. Probably too many explicit steps. :)

Thanks!

**Comment by codenamev** [comment]
Closing this as it seems to be a dup of #123
