### ISSUE TITLE
Option to require LGTM from only one person?

### ISSUE THREAD

**Issue by tarngerine** [reenhanced/gitreflow#141]
im happy to see this project. we use phabricator at fb but for my side project i want to adopt a similar style with stacked diffs that turn into squashed commits when merging. 

i liked the lgtm requirement as a hack around github, but having EVERY person LGTM is a bit too rigorous for my workflow. possible to have an option to set?

**Comment by codenamev** [comment]
I think this makes sense. We've worked with teams before that had approval minimums set before. @nhance, feature?

**Comment by nhance** [comment]
This is a great idea! Let's make a config option and add a question to the initial `setup`

**Comment by pboling** [comment]
The teams I am on would want to use a 2x `LGTM` minimum.  Even with that I do still like the requirement that the last comment contain `LGTM`, so if a minimum of two is set, and three people have commented, if the last one is not `LGTM`, then the merge is aborted.

This way code reviews that add valid questions can supersede older, perhaps less rigorous, reviews.

**Comment by codenamev** [comment]
I'll work on getting this out.  Seems simple enough.  I think it makes sense to check for a final `LGTM` comment as well.

**Comment by pboling** [comment]
@nhance @codenamev we are working on this feature at @invoice2go and will have a PR within the next day or so.

**Comment by codenamev** [comment]
Fantastic!  Looking forward to seeing it :smile:
