### ISSUE TITLE
review doesn't work with github forked repos.

### ISSUE THREAD

**Issue by squaresurf** [reenhanced/gitreflow#142]
`git reflow review` will create a Pull Request against the master branch of the forked repo not the original repo as expected.

**Comment by codenamev** [comment]
We've got this planned for our "Workflow" refactor.  Ultimately we need to extract our workflow and allow for for "hooks" so that people can customize the process.

We have an initial discussion going on how to apply this to open-source contributions here: #103

**Comment by squaresurf** [comment]
That sounds awesome! I was going to see if there was something about hooks. I need to add in trello integration eventually.

**Comment by codenamev** [comment]
We've got Trello integration nearly done as well (see the `vs-add-stage-command-and-trello` branch)!  Should be released sometime in November.  We recently did a fairly large overhaul to how we handle pull requests that I have not yet had the time to merge up so if you feel adventurous and want to explore it, I'd give it until next week so I can resolve all the conflicts.
