### ISSUE TITLE
git: 'reflow' is not a git command. See 'git --help'

### ISSUE THREAD

**Issue by shivhg** [reenhanced/gitreflow#146]
Error: 

    git reflow
    git: 'reflow' is not a git command. See 'git --help'.
    
    Did you mean this?
    	reflog git reflow command is not recognised, 

I have installed both git and `git_reflow` gem and even tried uninstalling and reinstalling the reflow and     updating the git version.

Current versions installed are :
git_reflow 0.7.1,
git version 2.6.3,
ruby 2.2.3p173

**Comment by codenamev** [comment]
Sorry for the late response here.  This sounds like you're having an issue with your `PATH`.  Run `echo $PATH` in your command line.  Are you using RVM or rbenv?

**Comment by shivhg** [comment]
I am using rbenv. I had issue issue due to multiple ruby version, i installed the gem in some other version. So was facing the issue. Not any issue so closing it
