### ISSUE TITLE
Remove unused gitreflow-common

### ISSUE THREAD

**Issue by pboling** [reenhanced/gitreflow#154]
## gitreflow-common is unused

So remove it!

## Original

```
#    http://github.com/nvie/gitreflow
```

is not a repository.  Was probably munged in an over-eager find-replace.

reference: https://github.com/nvie/gitflow/blob/develop/git-flow#L10

**Comment by pboling** [comment]
Also, it is unclear to me if the gitflow-common `sh` functions are used by git reflow.  Are they required for the project to work?  It seems to me that git reflow does not actually use the git flow flow.

**Comment by codenamev** [comment]
In the very beginning of this project we had hoped to build on top of a
modified version of git-flow, but it proved too cumbersome to maintain and
extend. I think we just missed yanking this file.  Can you update your PR
to just remove it?

Thanks for all the help :smile:

On Friday, April 8, 2016, Peter Boling <notifications@github.com
<javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:

> Also, it is unclear to me if the gitflow-common sh functions are used by
> git reflow. Are they required for the project to work? It seems to me that
> git reflow does not actually use the git flow flow.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/reenhanced/gitreflow/issues/154#issuecomment-207655613>
>


-- 

Cheers,
Valentino

**Comment by pboling** [comment]
Yep!
