### ISSUE TITLE
--base switch does not work?

### ISSUE THREAD

**Issue by talexand** [reenhanced/gitreflow#174]
```
git reflow start issue#2 --base dev
error: Unknown option --base
```

Running OSX with git-reflow cloned and built from 2dab9f7.

**Comment by simonzhu24** [comment]
@talexand 

Can you please make sure your git reflow repository is up to date (`git pull`), delete and rebuild your gem? 

I just tried it and It works for me currently:
```
Dev-Loaner-3s-MacBook-Pro:test ximengzhu$ git reflow start issue#2 --base 12345
Switched to branch '12345'
From https://github.com/simonzhu24/test
 * branch            12345      -> FETCH_HEAD
Total 0 (delta 0), reused 0 (delta 0)
To https://github.com/simonzhu24/test.git
 * [new branch]      12345 -> issue#2
Switched to a new branch 'issue#2'
```

**Comment by pboling** [comment]
`gem install git_reflow` won't work because `master` branch changes haven't been released yet.

**Comment by codenamev** [comment]
One last note here, `bundle exec rake install` will install the gem from source.  We should expect an official release by tomorrow :smile:
