### ISSUE TITLE
Bitbucket setup not working

### ISSUE THREAD

**Issue by dskrvk** [reenhanced/gitreflow#186]
Our team uses Bitbucket, where we have a team account, but everyone pushes changes under their personal accounts, so we can see who did what.
Is this use case supported?

I couldn't find any documentation on what "team-owned repos only" means, so this is what I tried:

> Which service would you like to use for this project?  2
> Please enter your BitBucket username: {team name here}
> Please enter your team's API key: {team API key}
> [error] Invalid API key for team {my personal BB username}

I also tried providing my personal username in the second step, with the same result.

**Comment by codenamev** [comment]
I'll look into this.  We use our team to own all repos, and the last we used Bitbucket, their API only supported calls to a repository that was owned by a team to use keys generated for that team.

**Comment by dskrvk** [comment]
All our repos are team-owned as well. People authenticate using their private HTTP/SSH credentials though.

**Comment by codenamev** [comment]
Unfortunately this is not supported by Bitbucket 😞 . See Bitbucket Issue [\#10182](https://bitbucket.org/site/master/issues/10182/access-tokens-for-command-line-use) for the current problem and workaround that we've chosen, and [\#12186](https://bitbucket.org/site/master/issues/12186/non-expiring-auth-access-tokens-bb-15425) to track the current status from Bitbucket.

**Comment by dskrvk** [comment]
So the use case that's currently supported is for all team members to use the team's credentials locally?

**Comment by codenamev** [comment]
Yes.  User access tokens are not supported on Bitbucket, but team access tokens are.
