### ISSUE TITLE
git-reflow setup not working on Windows

### ISSUE THREAD

**Issue by swestner** [reenhanced/gitreflow#187]
Every time I try and `git reflow review` reflow prompts me for my github username, password and then fails if a token exists, or passes and creates a new token (in which case it fails on the next review). 

If it fails because the token exists, it fails with the following error message

```
[error] You have previously setup git-reflow on this machine, but we can no longer find the stored token.
[notice] Please visit https://github.com/settings/tokens and delete the token for: git-reflow (Dell-PC-12)
[error]
```

**Comment by codenamev** [comment]
Github has recently changed their OAuth API and we have been fighting to find a way to resolve these issues.

Long story short, if you are on a version of git-reflow prior to `0.8.1` and you re-run the `setup` command you will likely run into this issue.  Can you try upgrading to the latest version? `gem update git-reflow`.  `git reflow --version` should say `0.8.1`

**Comment by swestner** [comment]
Interesting. Looking at the --version, I am on version 0.8.1. I just installed the package today. I notice that you are using a different package name than I installed with. IIRC I used `gem install git_reflow` as shown in the readme. I just tried `gem install git-reflow` which installs version 0.0.1, but if I run update on it I get a no package found

![image](https://cloud.githubusercontent.com/assets/6485583/15880751/30c2c214-2cfe-11e6-8e8b-cad3f0518aaf.png)

**Comment by codenamev** [comment]
`git-reflow` is an alias gem we setup that just includes `git_reflow` as a dependency (without targeting a version).  So if you were to `gem update git-reflow` it would update it's dependencies, and in turn get the latest `git_reflow`.

Can you paste your `~/.gitconfig.reflow` file please?

**Comment by swestner** [comment]
I see what is happening now. The application is creating a directory named `~` and putting the config file in there. 

![image](https://cloud.githubusercontent.com/assets/6485583/15897770/c4ec12aa-2d63-11e6-9525-747d0d4871fc.png)

![image](https://cloud.githubusercontent.com/assets/6485583/15897792/db743e3a-2d63-11e6-8de5-19e53988fe30.png)

After moving that file into place, it all works.

FYI : I am running powershell in administration mode through conemu on windows 10

**Comment by codenamev** [comment]
That would do it!  We haven't officially supported windows yet, but this is very helpful 😄 

I'll keep this issue open as a bug so we can keep track of it and we can address the setup and official support for windows in the next major release.

If you find any other bugs while working, please post an issue and I'll set a milestone to get this out :smile:

**Comment by codenamev** [comment]
@swestner can you paste the output from `echo $HOME`?  If that outputs the right directory this could be an easy fix.

**Comment by swestner** [comment]
![image](https://cloud.githubusercontent.com/assets/6485583/15900309/0f973880-2d6d-11e6-8c9b-5527839f01ca.png)

which is correctly identifies the home directory

**Comment by yfebles** [comment]
I had the same problem when i was installing  on windows. I modify the config.rb file on the line
5 when the CONFIG_FILE_PATH is defined for gitreflow config file storage

I put     CONFIG_FILE_PATH = "/.gitconfig.reflow".freeze and works. You must put here a path that is available on windows and not only the ~... that works good on unix and macs but not in windows

Maybe the constant value could be redefined to another path on windows OS installation in the next version.
