### ISSUE TITLE
undefined method for strip

### ISSUE THREAD

**Issue by abbas999** [reenhanced/gitreflow#197]
I'm trying to set up reflow but am getting an `undefined method 'strip' for /(?i-mx:lgtm|looks good to me|:\+1:|:thumbsup:|:shipit:)/:Regexp` error

reflow version is 0.8.3 and this is on CentOS. Ruby version is 2.2.4 (but i've also tried on 2.3.x with the same result).

    [ec2-user@ip-172-31-53-203 pict]$ git reflow setup
    [notice] Created $HOME/.gitconfig.reflow for Reflow specific configurations
    [notice] Added $HOME/.gitconfig.reflow to ~/.gitconfig include paths
    Available remote Git Server services:
    1. GitHub
    2. BitBucket (team-owned repos only)
    Which service would you like to use for this project?  1
    Your GitHub account was already setup with: 
    	User Name: 
    	Endpoint: https://api.github.com
    Set the minimum number of approvals (leaving blank will require approval from all commenters): 1
    error: undefined method `strip' for /(?i-mx:lgtm|looks good to me|:\+1:|:thumbsup:|:shipit:)/:Regexp

**Comment by codenamev** [comment]
I just came across this when reworking the tests as well.  That is the last configuration you need, so you can set it manually for now until release later today: `git config -f $HOME/.gitconfig.reflow --replace-all constants.approvalRegex "/(?i-mx:lgtm|looks good to me|:\+1:|:thumbsup:|:shipit:)/"`

**Comment by abbas999** [comment]
I'm still getting the same error even after adding the config param

**Comment by codenamev** [comment]
Fixed with dc80ebd59a49e4b01d60ad695ab393db7865a819 in v0.8.4
