### ISSUE TITLE
Make a git-reflow specific configuration for storing a custom base-branch

### ISSUE THREAD

**Issue by NamPNQ** [reenhanced/gitreflow#202]

**Comment by codenamev** [comment]
There is currently a way to provide custom base-branches to `start`, `review`, and `deliver` commands.  I agree with @NamPNQ it would be nice to have a usable reflow configuration to override the default `master`.

Relevant uses of base branch defaults here:

- [ ] [start command](https://github.com/reenhanced/gitreflow/blob/master/lib/git_reflow/commands/start.rb#L12)
- [ ] [refresh command](https://github.com/reenhanced/gitreflow/blob/master/lib/git_reflow/commands/refresh.rb#L14)
- [ ] [GitReflow::GitServer::BitBucket::PullRequest](https://github.com/reenhanced/gitreflow/blob/master/lib/git_reflow/git_server/bit_bucket/pull_request.rb#L33)
- [ ] [GitReflow::GitServer::GitHub::PullRequest](https://github.com/reenhanced/gitreflow/blob/master/lib/git_reflow/git_server/git_hub/pull_request.rb#L27)
- [ ] [start in core workflow](https://github.com/reenhanced/gitreflow/blob/master/lib/git_reflow/workflows/core.rb#L50)
- [ ] [review in core workflow](https://github.com/reenhanced/gitreflow/blob/master/lib/git_reflow/workflows/core.rb#L69)
- [ ] [status in core workflow](https://github.com/reenhanced/gitreflow/blob/master/lib/git_reflow/workflows/core.rb#L133)
- [ ] [deliver in core workflow](https://github.com/reenhanced/gitreflow/blob/master/lib/git_reflow/workflows/core.rb#L197)
- [ ] [refresh in core workflow](https://github.com/reenhanced/gitreflow/blob/master/lib/git_reflow/workflows/core.rb#L233)

**Comment by sangaline** [comment]
I agree that it would be nice to store the base branch, but another useful enhancement would be to include the ways to specify the base branch in the help menus of the commands. For example, the output of `git reflow deliver --help` is

```
NAME
    deliver - deliver your feature branch

SYNOPSIS
    git-reflow [global options] deliver [command options] 

DESCRIPTION
    merge your feature branch down to your base branch, and cleanup your feature branch 

COMMAND OPTIONS
    -f, --[no-]skip-lgtm - skip the lgtm checks and deliver your feature branch
```

which doesn't mention at all that there's an optional positional argument for the base branch. The help menu for the review command does mention the base branch, but it seems to suggest that you use the `--title` option which isn't correct.

```
NAME
    review - review will push your latest feature branch changes to your remote repo and create a pull request

SYNOPSIS
    git-reflow [global options] review [command options] Describe arguments to review here

COMMAND OPTIONS
    -m, --message=arg                                                                        - (default: none)
    -t, --title=[destination_branch] - the branch you want to merge your feature branch into - push your latest feature branch changes to your remote repo and create a pull request against the destination branch (default: none)
```

For anybody finding this from Google, the ways to specify the base branches are:

```
git reflow start -b base-branch new-branch
git reflow refresh -b base-branch
git reflow review base-branch
git reflow deliver base-branch
```
