### ISSUE TITLE
Github approval message is not seen as a LGTM

### ISSUE THREAD

**Issue by zwippie** [reenhanced/gitreflow#207]
With the introduction of [Github review requests](https://github.com/blog/2291-introducing-review-requests), it is now possible to give a comment on a PR as an **approval**.

Unfortunately, these approval messages are not seen by gitreflow as a valid `LGTM`, even if the text of the approval message is `LGTM`.

**Comment by codenamev** [comment]
This was waiting on the github_api to pull in [our updates for the new API endpoints](https://github.com/piotrmurach/github/pull/292).  Now that v0.16 has been released, I've been working to resolve a namespace conflict with a global `say` command that was introduced with v0.15.  This may have to wait until git_reflow `0.9.0`.  Lots of exciting new features coming 😉

**Comment by nhance** [comment]
@codenamev Check the latest master, I think I was able to get around the `say` conflict with `0.8.6` but I forget the details
