### ISSUE TITLE
ear

### ISSUE THREAD

**Issue by XenuxX** [reenhanced/gitreflow#225]

**Comment by nhance** [comment]
👂

**Comment by XenuxX** [comment]
Sorry for that. I was moving my cursor from Windows to VM. I didn’t reaize
that it was being typed as comment when i was trying to type in my VM.
Sorry again.

**Comment by nhance** [comment]
No problem! I'll close this.. If you have any suggestions for new features, we're all 👂 👂 👂 👂 👂
