### ISSUE TITLE
command for merging updates from base branch

### ISSUE THREAD

**Issue by rarkins** [reenhanced/gitreflow#74]
As a policy, we ask developers to merge updates from the base branch (e.g. master) prior to submitting or resubmitting a PR for review. Due to merge squashing, it won't matter how many messy merge commits come, so this is good practice for a project where people are committing things that don't cause merge conflict but could still cause problems. A reflow command for this would be good.

**Comment by codenamev** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;v4yoxMub&#x2F;22-164-issue-66-74-implementing-git-reflow-refresh"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> [164] [Issue #66 + #74] Implementing &quot;Git Reflow Refresh&quot;</a>

**Comment by codenamev** [comment]
Fixed in v0.8.0 with 3b44510b7042f7aa6db76248aa52123145732c0a. `git reflow refresh` :smile:
