### ISSUE TITLE
Changing remote url in \reponame\.git\config to make reflow deliver work

### ISSUE THREAD

**Issue by aqilzeeshan** [reenhanced/gitreflow#75]
for "git reflow deliver branch_name" to work, I have to change 
C:\Users\Administrator\Documents\GitHub\reponame\.git\config
From 
[remote "origin"]
	url = https://username:password@github.com/accountowner/reponame.git
	fetch = +refs/heads/*:refs/remotes/origin/*
To
[remote "origin"]
	fetch = +refs/heads/*:refs/remotes/origin/*
	url = git@github.com:accountowner/reponame.git

Is it known issue ?
otherwise it does not work.

**Comment by codenamev** [comment]
Fixed in `0.4.2` :smile:
