### ISSUE TITLE
404 error on all PR functions

### ISSUE THREAD

**Issue by seaneking** [reenhanced/gitreflow#77]
Getting a 404 error when git reflow tries to do anything on a pull request. `review` fails, and even if I make a PR manually for the branch `delver` and `status` also fail.

Tried to re-run `git reflow setup` but it just tells me that 
```
Your GitHub account was already setup with:   
 	User Name:   
	Endpoint: https://api.github.com  
```
as does `git reflow setup -l`  

Example of one of the errors (on `review`):
```Error: #<Github::Error::NotFound: GET https://api.github.com/repos/github.com/sproutli/pulls?access_token=32162b54b3c8501f6b260e37b8a7f3d88cfc3d53%0A&base=master&head=github.com%3Aselectize&state=open: 404 Not Found>```

My collaborator is getting the same error.

**Comment by codenamev** [comment]
@seaneking what is the name of the repo/branch?  We've had issues in the past with branch and repo names that have special characters and have been trying to hone how we parse it from the URL.

**Comment by seaneking** [comment]
no special characters, repo is `seaneking/sproutli` and branches I've tried with are just standard words (e.g: `selectize`). Though I notice that the GET api url in the error above isn't right? Should be `github.com/seaneking/sproutli/`.

Also, probably not related, but another project I've been dealing with in the last few days (dokku-alt) has had similar 404 errors due to a change in how gh-pages are handled, so not sure if github have changed anything related on their end.

**Comment by codenamev** [comment]
We are parsing the remote user and remote repo name manually from the origin URL you setup your project with (see: [GitHelpers](https://github.com/reenhanced/gitreflow/blob/master/lib/git_reflow/git_helpers.rb#L8))

Looks like somehow the wrong settings are ending up in your gitconfig.  Can you paste here what you have in your project's .git/config file for `remote.origin.url`?

**Comment by seaneking** [comment]
url = https://github.com/seaneking/sproutli.git

**Comment by codenamev** [comment]
Ah, this is related to #75 caused by #71.  To fix this, you can patch up your origin to use the `git://` url for the repo as opposed to the `http://` url you're using.

`git remote set-url origin git://new.url.here`
