### ISSUE TITLE
Review command race condition

### ISSUE THREAD

**Issue by codenamev** [reenhanced/gitreflow#84]
Sometimes the pull request trying to get created for a branch that doesn't exist yet.  Need to wait for the initial push before we can create the pull request.

**Comment by codenamev** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;GDrqplB7&#x2F;32-review-command-race-condition"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Review command race condition</a>

**Comment by simonzhu24** [comment]
@codenamev can you provide more details on this bug? The trello card seems to have been deleted.
