### ISSUE TITLE
bad URI on git reflow status

### ISSUE THREAD

**Issue by mms-uret** [reenhanced/gitreflow#88]
When executing `git reflow status` I get

`error: bad URI(is not URI?): https://api.github.com`

commands which do not use GitHub API (eg. start) work as expected.

Any ideas? Thanks in advance.

**Comment by nhance** [comment]
I saw this when using ruby 2.2.0 as well. Looks like an issue with the latest ruby. Can you try 2.1.5? We'll use this ticket to address

**Comment by codenamev** [comment]
We should really add tests for multiple versions of ruby and dependencies
like this:
http://ylan.segal-family.com/blog/2013/06/21/testing-with-multiple-ruby-and-gem-versions/

We can add this in to relieve this and future related issues

**Comment by mms-uret** [comment]
Thanks a lot, works with ruby 2.1.5
