### ISSUE TITLE
Default PR title from branch name rather than last commit

### ISSUE THREAD

**Issue by seaneking** [reenhanced/gitreflow#89]
Or better yet enable user to edit title on command line before creating PR during deliver. We have Slack notifications setup for PRs and having all these random PR titles pop up is confusing/annoying, especially for non-devs on the team who keep up with app progress.

**Comment by nhance** [comment]
I agree, this has been a slight annoyance. It's probably not too much to prompt for a title and we could allow it to be specified with `-m "title here"` which is something devs are probably used to

**Comment by seaneking** [comment]
Yep I think prompting during review + an `-m` shortcut for this would be awesome. Unless they’re planning on pushing straight through with `—skip-lgtm` then the dev would have to set a better title on the PR anyway, so may as well do it during review.

**Comment by codenamev** [comment]
I agree, I find myself modifying the PR title every time anyways.  I'll see about adding this soon.

**Comment by codenamev** [comment]
@seaneking we've updated this in the latest version
