### ISSUE TITLE
bitbucket: error occurs while creating pull request

### ISSUE THREAD

**Issue by frankhock** [reenhanced/gitreflow#93]
http://take.ms/I1b8k

screenshot of error :point_up: 
alias `grr` - git reflow review

reflow successfully creates PR and assigns reviewer, however it does not open browser for review

**Comment by omranjamal** [comment]
The link above returns XML saying 'Access Denied', but I think I'm having a similar problem.

**Comment by nhance** [comment]
We're going to be putting another cycle on this perhaps as soon as next week. This is on the top of the list to review as soon as we can get some time on it

**Comment by codenamev** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;eM2YkXQz&#x2F;34-bitbucket-error-occurs-while-creating-pull-request"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> bitbucket: error occurs while creating pull request</a>

**Comment by lcDan** [comment]
me2

**Comment by frozentech** [comment]
me3

**Comment by napoleon101392** [comment]
me4

**Comment by sandergarretsen** [comment]
me5

**Comment by lcDan** [comment]
https://status.bitbucket.org/

**Comment by codenamev** [comment]
Is this still an issue?

**Comment by codenamev** [comment]
Closing this until it presents itself again.  I believe this has been resolved.
