### ISSUE TITLE
Git reflow setup undefined method `body`

### ISSUE THREAD

**Issue by warden1975** [reenhanced/gitreflow#96]
I have stumbled into this error suddenly. Can anyone help what could be the problem.

```error: undefined method `body' for #<ArgumentError: wrong number of arguments (2 for 1)>```

**Comment by codenamev** [comment]
what version of ruby are you using?

**Comment by warden1975** [comment]
```ruby -v
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin14]```

**Comment by warden1975** [comment]
```gem -v
2.4.6```

**Comment by warden1975** [comment]
Anybody who can help? Or any suggestion that I should do for further tests?

**Comment by warden1975** [comment]
@codenamev ?

**Comment by codenamev** [comment]
Can you provide a backtrace starting with what command you ran to get that?

**Comment by codenamev** [comment]
Closing this one for now.  If you have issues again we can re-open and re-visit.
