### ISSUE TITLE
tmp_squash_msg can be improved

### ISSUE THREAD

**Issue by tanin47** [reenhanced/gitreflow#97]
tmp_squash_msh seems to be hanging around if we use git reflow in other directories than root. This is due to this part of code.

```ruby
    def append_to_squashed_commit_message(message = '')
      run "echo \"#{message}\" | cat - .git/SQUASH_MSG > ./tmp_squash_msg"
      run 'mv ./tmp_squash_msg .git/SQUASH_MSG'
    end
```

If we are not the the root directory, the relative ./git won't exist

We can change to something like:

```ruby
    def append_to_squashed_commit_message(message = '')
     git_root_dir = `echo $(git rev-parse --show-toplevel)`
      run "echo \"#{message}\" | cat - #{git_root_dir}/.git/SQUASH_MSG > #{git_root_dir}/tmp_squash_msg"
      run 'mv #{git_root_dir}/tmp_squash_msg #{git_root_dir}/.git/SQUASH_MSG'
    end
```

**Comment by codenamev** [comment]
That's a great idea. Nice catch!  Care to submit a pull request? This would
be a great method to have in our `git_helpers` in `
lib/git_reflow/git_helpers.rb`
